name: Run tests

on:
  pull_request:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:
    inputs:
      verilator_version:
        description: 'Verilator version to use for testing'
        required: true
        default: 'V4.228'
        type: choice
        options:
          - 'V4.228'
          - 'V5.022'
          - 'V5.024'

jobs:
  run-sbt-tests:
    uses: ./.github/workflows/sbt-tests.yml
    with:
      scala_version: '2.12.18'
      runner_os: 'Linux'
      github_sha: ${{ github.sha }}
      verilator_version: ${{ github.event.inputs.verilator_version || 'V4.228' }}

  scaladoc:
    needs: run-sbt-tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-compiled
    - run: sbt unidoc
